name: eisenhower_matrix
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils:
  cupertino_icons: ^1.0.2 # Adds the Cupertino Icons font to your application.
  get: ^4.6.5
  auto_size_text: ^3.0.0 # Flutter widget that automatically resizes text to fit perfectly within its bounds.

  # Animations
  convex_bottom_bar: ^3.1.0+1 # Implements a ConvexAppBar to show a convex tab in the bottom bar.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utils:
  flutter_lints: ^2.0.0 # Recommended lints to encourage good coding practices.

flutter:
  uses-material-design: true
